[package]
name = "mysql_user_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "24.0.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.11.0"
env_logger = "0.10"