CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID，自增',
    uuid BINARY(16) NOT NULL COMMENT '全局唯一标识符（二进制格式）',
    username VARCHAR(255) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    email VARCHAR(255) NOT NULL COMMENT '电子邮箱',
    age INT COMMENT '年龄',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY unique_uuid (uuid),
    UNIQUE KEY unique_email (email)
) COMMENT='用户信息表';
