//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "github_commits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sha: String,
    pub node_id: String,
    pub author_name: String,
    pub author_email: String,
    pub commit_date: DateTime,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub tree_sha: String,
    pub url: String,
    pub html_url: String,
    pub comments_url: String,
    pub comment_count: i32,
    pub parent_sha: Option<String>,
    pub parent_url: Option<String>,
    pub verified: i8,
    pub verify_reason: Option<String>,
    pub created_at: DateTime,
    pub repository: String,
    pub branch: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
