//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "library_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub library_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::TagId",
        to = "super::tags::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tags,
    #[sea_orm(
        belongs_to = "super::third_party_libraries::Entity",
        from = "Column::LibraryId",
        to = "super::third_party_libraries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ThirdPartyLibraries,
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl Related<super::third_party_libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThirdPartyLibraries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
