//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
use crate::models::sluice_data::timestamp_to_formatted_string;
use crate::models::sluice_devices::{self};
use crate::models::user::{self};
use crate::AppError;
use sea_orm::entity::prelude::*;
use sea_orm::{
    ColumnTrait, DatabaseConnection, EntityTrait, FromQueryResult, JoinType, QueryFilter,
    QueryOrder, QuerySelect,
};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;

#[derive(Debug, Clone, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sluice_command")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "CONTENT")]
    pub content: String,

    #[sea_orm(column_name = "PUSH_STATUS")]
    pub push_status: i8,
    #[sea_orm(column_name = "DEVICE_ID")]
    pub device_id: Option<String>,
    #[sea_orm(column_name = "USER_ID")]
    pub user_id: i64,
    pub create_time: i64,
    pub topic: String,
    pub device_info: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    User,
    // 查询设备表里面的设备名称
    #[sea_orm(
        belongs_to = "super::sluice_devices::Entity",
        from = "Column::Topic",
        to = "super::sluice_devices::Column::PublishTopic",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SluiceDevices,
}
impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}
impl Related<super::sluice_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SluiceDevices.def()
    }
}

impl From<Model> for JsonValue {
    fn from(model: Model) -> JsonValue {
        serde_json::to_value(model).unwrap()
    }
}

impl TryFrom<JsonValue> for Model {
    type Error = serde_json::Error;

    fn try_from(value: JsonValue) -> Result<Self, Self::Error> {
        serde_json::from_value(value)
    }
}
#[derive(FromQueryResult, Debug, Clone, Serialize, Deserialize)]
pub struct SluiceWithUsername {
    // 主表字段
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "CONTENT")]
    pub content: Option<String>,
    #[sea_orm(column_name = "PUSH_STATUS")]
    pub push_status: Option<i8>,
    #[sea_orm(column_name = "DEVICE_ID")]
    pub device_id: Option<String>,
    pub create_time: i64,
    pub user_name: String,
    #[sea_orm(column_name = "TOPIC")]
    pub topic: String,
    pub device_name: String,
    pub create_time_str: Option<String>,
    pub device_info: Option<String>,
}

impl SluiceWithUsername {
    pub fn from_model(model: SluiceWithUsername) -> Self {
        SluiceWithUsername {
            id: model.id,
            content: model.content,
            create_time_str: Some(timestamp_to_formatted_string(model.create_time)), // 使用 Utc.timestamp 方法
            push_status: model.push_status,
            device_id: model.device_id,
            user_name: model.user_name,
            topic: model.topic,
            device_name: model.device_name,
            create_time: model.create_time,
            device_info: model.device_info,
            // 其他字段...
        }
    }
}
impl Entity {
    pub async fn find_with_user(
        db: &DatabaseConnection,
        start_time: i64,
        end_time: i64,
        topic: &str,
    ) -> Result<Vec<SluiceWithUsername>, AppError> {
        let model_results = Self::find()
            .filter(Column::Topic.eq(topic))
            .filter(Column::CreateTime.gte(start_time))
            .filter(Column::CreateTime.lte(end_time))
            .order_by_desc(Column::Id)
            .join(JoinType::InnerJoin, Relation::User.def())
            .join(JoinType::InnerJoin, Relation::SluiceDevices.def())
            .select_only() // 关键：只选择指定字段
            .column_as(Column::Id, "id")
            .column_as(Column::Content, "content")
            .column_as(Column::PushStatus, "push_status")
            .column_as(Column::DeviceId, "device_id")
            .column_as(Column::CreateTime, "create_time")
            .column_as(Column::Topic, "topic")
            .column_as(Column::DeviceInfo, "device_info")
            .column_as(user::Column::UserName, "user_name") // 设置别名
            .column_as(sluice_devices::Column::DeviceName, "device_name")
            .into_model::<SluiceWithUsername>()
            .all(db)
            .await
            .map_err(|e| AppError::InternalServerError(format!("数据库操作失败: {}", e)))?;
        let results: Vec<SluiceWithUsername> = model_results
            .into_iter()
            .map(|model| SluiceWithUsername::from_model(model)) // 使用自定义的 from_model 函数进行转换
            .collect();
        log::info!("查询结果: {:?}", results.len());
        Ok(results)
    }
}
impl ActiveModelBehavior for ActiveModel {}
