//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
#[derive(Debug, Clone, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sluice_data")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "LVLL", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvll: Option<Decimal>,
    #[sea_orm(column_name = "LVLH", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlh: Option<Decimal>,
    #[sea_orm(column_name = "CTRLMOD")]
    pub ctrlmod: Option<i8>,
    #[sea_orm(column_name = "OPENSTA")]
    pub opensta: Option<i8>,
    #[sea_orm(
        column_name = "OPENHGT",
        column_type = "Decimal(Some((10, 3)))",
        nullable
    )]
    pub openhgt: Option<Decimal>,
    #[sea_orm(column_name = "LVLB", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlb: Option<Decimal>,
    #[sea_orm(column_name = "LVLA", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvla: Option<Decimal>,
    #[sea_orm(column_name = "ICCID")]
    pub iccid: Option<String>,
    #[sea_orm(column_name = "VBAT", column_type = "Decimal(Some((10, 2)))", nullable)]
    pub vbat: Option<Decimal>,
    #[sea_orm(column_name = "CSTAMP")]
    pub cstamp: Option<i64>,
    #[sea_orm(column_name = "CSQ")]
    pub csq: Option<i32>,
    #[sea_orm(column_name = "LO", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub lo: Option<Decimal>,
    #[sea_orm(column_name = "LA", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub la: Option<Decimal>,
    pub sluice_id: String,
    // #[sea_orm(column_name = "CREATE_TIME")]
    // pub create_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for JsonValue {
    fn from(model: Model) -> JsonValue {
        serde_json::to_value(model).unwrap()
    }
}

impl TryFrom<JsonValue> for Model {
    type Error = serde_json::Error;

    fn try_from(value: JsonValue) -> Result<Self, Self::Error> {
        serde_json::from_value(value)
    }
}

impl ActiveModelBehavior for ActiveModel {}
