//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
use crate::models::sluice_devices::{self};
use crate::AppError;
use chrono::offset::LocalResult;
use chrono::{FixedOffset, TimeZone, Utc};
use sea_orm::{entity::prelude::*, JoinType, QueryOrder, QuerySelect};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
#[derive(Debug, Clone, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sluice_data")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "LVLL", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvll: Option<Decimal>,
    #[sea_orm(column_name = "LVLH", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlh: Option<Decimal>,
    #[sea_orm(column_name = "CTRLMOD")]
    pub ctrlmod: Option<i8>,
    #[sea_orm(column_name = "OPENSTA")]
    pub opensta: Option<i8>,
    #[sea_orm(
        column_name = "OPENHGT",
        column_type = "Decimal(Some((10, 3)))",
        nullable
    )]
    pub openhgt: Option<Decimal>,
    #[sea_orm(column_name = "LVLB", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlb: Option<Decimal>,
    #[sea_orm(column_name = "LVLA", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvla: Option<Decimal>,
    #[sea_orm(column_name = "ICCID")]
    pub iccid: Option<String>,
    #[sea_orm(column_name = "VBAT", column_type = "Decimal(Some((10, 2)))", nullable)]
    pub vbat: Option<Decimal>,
    #[sea_orm(column_name = "CSTAMP")]
    pub cstamp: Option<i64>,
    #[sea_orm(column_name = "CSQ")]
    pub csq: Option<i32>,
    #[sea_orm(column_name = "LO", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub lo: Option<Decimal>,
    #[sea_orm(column_name = "LA", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub la: Option<Decimal>,
    pub sluice_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sluice_devices::Entity",
        from = "Column::SluiceId",
        to = "super::sluice_devices::Column::SubscribeTopic",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SluiceDevices,
}

impl From<Model> for JsonValue {
    fn from(model: Model) -> JsonValue {
        serde_json::to_value(model).unwrap()
    }
}

impl TryFrom<JsonValue> for Model {
    type Error = serde_json::Error;

    fn try_from(value: JsonValue) -> Result<Self, Self::Error> {
        serde_json::from_value(value)
    }
}

#[derive(sea_orm::FromQueryResult, Debug, Clone, Serialize, Deserialize)]
pub struct SluiceWithUsername {
    // #[sea_orm(column_name = "ID", primary_key)]
    // pub id: i64,
    #[sea_orm(column_name = "LVLL", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvll: Option<Decimal>,
    #[sea_orm(column_name = "LVLH", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlh: Option<Decimal>,
    #[sea_orm(column_name = "CTRLMOD")]
    pub ctrlmod: Option<i8>,
    #[sea_orm(column_name = "OPENSTA")]
    pub opensta: Option<i8>,
    #[sea_orm(
        column_name = "OPENHGT",
        column_type = "Decimal(Some((10, 3)))",
        nullable
    )]
    pub openhgt: Option<Decimal>,
    #[sea_orm(column_name = "LVLB", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvlb: Option<Decimal>,
    #[sea_orm(column_name = "LVLA", column_type = "Decimal(Some((10, 3)))", nullable)]
    pub lvla: Option<Decimal>,
    #[sea_orm(column_name = "ICCID")]
    pub iccid: Option<String>,
    #[sea_orm(column_name = "VBAT", column_type = "Decimal(Some((10, 2)))", nullable)]
    pub vbat: Option<Decimal>,
    #[sea_orm(column_name = "CSTAMP")]
    pub cstamp: Option<i64>,
    #[sea_orm(column_name = "CSQ")]
    pub csq: Option<i32>,
    #[sea_orm(column_name = "LO", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub lo: Option<Decimal>,
    #[sea_orm(column_name = "LA", column_type = "Decimal(Some((12, 7)))", nullable)]
    pub la: Option<Decimal>,
    pub sluice_name: String,
    pub create_time: Option<String>,
}
pub fn timestamp_to_formatted_string(timestamp: i64) -> String {
    let beijing_tz: FixedOffset = FixedOffset::east(8 * 3600);

    // 将 UTC 时间转换为东八区时间，使用 timestamp_opt() 方法
    let beijing_time = match Utc.timestamp_opt(timestamp as i64, 0) {
        LocalResult::Single(datetime) => datetime,
        _ => {
            log::error!("Invalid timestamp: {}", timestamp);
            Utc.timestamp(0, 0)
        }
    };
    let datetime_bj = beijing_time.with_timezone(&beijing_tz);
    // 格式化日期时间为 "%Y-%m-%d %H:%M:%S" 格式
    datetime_bj.format("%Y-%m-%d %H:%M:%S").to_string()
}
impl SluiceWithUsername {
    pub fn from_model(model: SluiceWithUsername) -> Self {
        SluiceWithUsername {
            sluice_name: model.sluice_name,
            create_time: Some(timestamp_to_formatted_string(model.cstamp.unwrap())), // 使用 Utc.timestamp 方法
            lvll: model.lvll,
            lvlh: model.lvlh,
            ctrlmod: model.ctrlmod,
            opensta: model.opensta,
            openhgt: model.openhgt,
            lvlb: model.lvlb,
            lvla: model.lvla,
            iccid: model.iccid,
            vbat: model.vbat,
            cstamp: model.cstamp,
            csq: model.csq,
            lo: model.lo,
            la: model.la,
            // 其他字段...
        }
    }
}
impl Entity {
    pub async fn find_with_user(
        db: &DatabaseConnection,
        start_time: i64,
        end_time: i64,
        topic: &str,
    ) -> Result<Vec<SluiceWithUsername>, AppError> {
        let model_results = Self::find()
            .filter(Column::SluiceId.eq(topic))
            .filter(Column::Cstamp.gte(start_time))
            .filter(Column::Cstamp.lte(end_time))
            .order_by_desc(Column::Id)
            .join(JoinType::InnerJoin, Relation::SluiceDevices.def())
            .select_only() // 关键：只选择指定字段
            .column_as(Column::Id, "id")
            .column_as(Column::Lvla, "lvla")
            .column_as(Column::Lvll, "lvll")
            .column_as(Column::Lvlh, "lvlh")
            .column_as(Column::Ctrlmod, "ctrlmod")
            .column_as(Column::Opensta, "opensta")
            .column_as(Column::Openhgt, "openhgt")
            .column_as(Column::Openhgt, "openhgt")
            .column_as(Column::Iccid, "iccid")
            .column_as(Column::Vbat, "vbat")
            .column_as(Column::Cstamp, "cstamp")
            .column_as(Column::Csq, "csq")
            .column_as(Column::Lo, "lo")
            .column_as(Column::La, "la")
            .column_as(Column::Id, "id")
            .column_as(sluice_devices::Column::DeviceName, "sluice_name")
            .into_model::<SluiceWithUsername>()
            .all(db)
            .await
            .map_err(|e| AppError::InternalServerError(format!("数据库操作失败: {}", e)))?;
        let results: Vec<SluiceWithUsername> = model_results
            .into_iter()
            .map(|model| SluiceWithUsername::from_model(model)) // 使用自定义的 from_model 函数进行转换
            .collect();
        Ok(results)
    }
}

impl ActiveModelBehavior for ActiveModel {}
